[package]
name = "xtask"
description = "Chartreuse build automation (`cargo xtask`)"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[dependencies]
chartreuse-core.workspace = true
png = "0.18.1"

[dev-dependencies]
plist = "1.10.1"

[lints]
workspace = true
